// peri.js
//


top.peri = [
    {"title": "d120 The character has the trait...", "id":"d120_CharacterTraits", "roll":
    [ 
        "Active", "Adventurous", "Affectionate", "Aggressive", "Agreeable", "Aloof", "Ambitious", "Angry", "Anxious", "Apathetic", "Arcane", "Arrogant", "Artistic", "Athletic", "Attractive", "Bitter", "Bold", "Brash", "Brave", "Calculating", "Careless", "Caring", "Cautious", "Charming", "Cheery", "Clever", "Clumsy", "Cold", "Conceited", "Confident", "Confused", "Connected", "Cooperative", "Corrupt", "Cowardly", "Critical", "Cruel", "Cunning", "Curious", "Dangerous", "Deceitful", "Dependent", "Determined", "Disabled", "Distracted", "Doomed", "Driven", "Dying", "Enigmatic", "Experienced", "Famous", "Fervent", "Friendly", "Generous", "Greedy", "Hardhearted", "Haunted", "Honest", "Hostile", "Hot-tempered", "Incompetent", "Infamous", "Influential", "Insensitive", "Insightful", "Intellectual", "Intolerant", "Jealous", "Kind", "Knowledgable", "Loyal", "Manipulative", "Meddler", "Moody", "Oblivious", "Observant", "Obsessed", "Oppressed", "Passive", "Patient", "Powerful", "Proud", "Quiet", "Quirky", "Reclusive", "Relaxed", "Religious", "Remorseful", "Resourceful", "Ruthless", "Secretive", "Selfish", "Serene", "Shrewd", "Sick", "Skilled", "Smug", "Sociable", "Sophisticated", "Stealthy", "Stern", "Stingy", "Stoic", "Strange", "Strong", "Stubborn", "Successful", "Suspicious", "Talented", "Timid", "Ugly", "Vain", "Vengeful", "Violent", "Wary", "Weak", "Wealthy", "Weary", "Wild", "Wise"
    ]},
    
    {"title": "d50 The character has the hook...", "id":"d50_CharacterHook", "roll":
    [ 
        "Missing a limb", "Visible prostetics", "Unusual hair, skin, or eye colors", "Scarring, either intentional or from old injuries", "Tic-like overuse of a particular word or phrase", "Specific unusual fragrance or cologne", "Constant fiddling with a particular item", "Visible sign of drug use", "Always seems to be in one particular mood", "Wear badges or marks of allegiance to a cause", "Extremely slow or fast pace of speech", "Wheezes, shakes, or other signs of infirmity", "Constantly with a drink to hand", "Always complaining about a group or organization", "Paranoid, possibly for justifiable reasons", "Insists on a particular location for all meetings", "Communicates strictly through a third party", "Abnormally obese or emaciated in build", "Always found with henchmen or friends", "Dresses far too young or old for them", "Unusually shabby or ill-kept clothing", "Cutting-edge fashion as they can afford", "Loud foreign clothing style", "Extremely muscular or spindly form", "Lacking or excessive in hair", "Unusually short or tall", "Taps toe or fingers constantly", "All motions are rough and vigorous", "Can't talk without gesturing", "Never looks directly at interlocutor", "Constantly glancing around", "Very obvious religious tokens are worn", "They have an unusual accent", "They're of an uncommon race for the area", "Extremely laconic or voluble", "Laughs at inappropriate moments", "Has some speech impediment", "Has a constant air of suspicion", "Has elaborate tattoos or skin-paintings", "Voice is extremely grating and unpleasant", "Recently wounded", "Missing an eye or facial feature", "Terrible taste in clothing", "Repeats himself constantly", "Speaks as little as possible", "Look diseased or have marks of disease", "Jewels or decorations in hair or beard", "Immaculate hairs/beard or fancy hairdo", "Speaks slowly, looks like drunk or dugged but is not", "Very young or very old"
    ]},

    {"title": "d100 The character is a...", "id":"d100_CharacterRole", "roll":
    [ 
        "Criminal", "Criminal", "Healer", "Healer", "Bandit", "Bandit", "Guide", "Guide", "Guide", "Performer", "Performer", "Performer", "Miner", "Miner", "Miner", "Mercenary", "Mercenary", "Mercenary", "Outcast", "Outcast", "Outcast", "Vagrant", "Vagrant", "Vagrant", "Forester", "Forester", "Forester", "Traveler", "Traveler", "Traveler", "Mystic", "Mystic", "Mystic", "Priest", "Priest", "Priest", "Sailor", "Sailor", "Sailor", "Pilgrim", "Pilgrim", "Pilgrim", "Thief", "Thief", "Thief", "Adventurer", "Adventurer", "Adventurer", "Forager", "Forager", "Forager", "Leader", "Leader", "Leader", "Guard", "Guard", "Guard", "Guard", "Artisan", "Artisan", "Artisan", "Artisan", "Scout", "Scout", "Scout", "Scout", "Herder", "Herder", "Herder", "Herder", "Fisher", "Fisher", "Fisher", "Fisher", "Warrior", "Warrior", "Warrior", "Warrior", "Warrior", "Hunter", "Hunter", "Hunter", "Hunter", "Hunter", "Raider", "Raider", "Raider", "Raider", "Raider", "Trader", "Trader", "Trader", "Trader", "Trader", "Farmer", "Farmer", "Farmer", "Farmer", "Farmer", "Unusual role"
    ]},

    {"title": "d100 The character has a simple goal of...", "id":"d100_CharacterSimpleGoals", "roll":
    [ 
        "Obtain an object", "Obtain an object", "Obtain an object", "Make an agreement", "Make an agreement", "Make an agreement", "Build a relationship", "Build a relationship", "Build a relationship", "Undermine a relationship", "Undermine a relationship", "Undermine a relationship", "Seek a truth", "Seek a truth", "Seek a truth", "Pay a debt", "Pay a debt", "Pay a debt", "Refute a falsehood", "Refute a falsehood", "Refute a falsehood", "Harm a rival", "Harm a rival", "Harm a rival", "Cure an ill", "Cure an ill", "Cure an ill", "Find a person", "Find a person", "Find a person", "Find a home", "Find a home", "Find a home", "Seize power", "Seize power", "Seize power", "Restore a relationship", "Restore a relationship", "Restore a relationship", "Create an item", "Create an item", "Create an item", "Travel to a place", "Travel to a place", "Travel to a place", "Secure provisions", "Secure provisions", "Secure provisions", "Rebel against power", "Rebel against power", "Rebel against power", "Collect a debt", "Collect a debt", "Collect a debt", "Protect a secret", "Protect a secret", "Protect a secret", "Spread faith", "Spread faith", "Spread faith", "Enrich themselves", "Enrich themselves", "Enrich themselves", "Protect a person", "Protect a person", "Protect a person", "Protect the status quo", "Protect the status quo", "Protect the status quo", "Advance status", "Advance status", "Advance status", "Defend a place", "Defend a place", "Defend a place", "Avenge a wrong", "Avenge a wrong", "Avenge a wrong", "Fulfill a duty", "Fulfill a duty", "Fulfill a duty", "Gain knowledge", "Gain knowledge", "Gain knowledge", "Prove worthiness", "Prove worthiness", "Prove worthiness", "Find redemption", "Find redemption", "Find redemption", "Escape from something", "Escape from something", "Resolve a dispute", "Resolve a dispute", "Resolve a dispute", "Roll twice", "Roll twice", "Roll twice", "Roll twice", "Roll twice"
    ]},

    {"title": "d100 The character has a compex goal of...", "id":"d100_CharacterComplexGoals", "roll":
    [ 
        "Access another dimension", "Alleviate feelings of guilt", "Amass an army", "Assume another’s identity", "Attend an event", "Attract a following", "Avoid responsibilities", "Become a martyr", "Become famous/infamous", "Become happy", "Become immortal", "Become wealthy", "Chronicle history", "Complete a mission", "Conquer a nation", "Continue a legacy", "Cure a disease", "Damage another’s reputation", "Delay a wedding", "Deliver a message", "Destroy a relationship", "Destroy an enemy", "Discover the truth", "Do good", "Earn money", "Eliminate a populace", "Eliminate a race", "Eliminate a threat", "Eliminate a weakness", "Enact revenge", "End a relationship", "End a war", "End suffering", "Enforce the law", "Entertain", "Escape punishment", "Establish a new identity", "Establish a relationship", "Exile someone", "Explore new territories", "Find a lost treasure", "Find a missing object or person", "Find someone", "Find spiritual enlightenment", "Frame someone", "Frighten", "Gain a reward", "Gain approval", "Gain attention", "Gain power", "Gain protection", "Gain trust", "Hide a secret", "Imprison another", "Improve someone’s social status", "Improve someone’s quality of life", "Increase a collection", "Inspire rebellion", "Investigate about something", "Lead others", "Make someone angry", "Make someone envious/jealous", "Make someone fail", "Make someone succeed", "Overturn a decision", "Pass an initiation", "Pay a debt", "Perform a religious ceremony", "Predict the future", "Prolong a war", "Promote peace", "Protect a reputation", "Prove self", "Prove someone’s innocence", "Reanimate the dead", "Reclaim property", "Regain control", "Regain fame or wealth", "Regain youth", "Relieve boredom", "Repair damage", "Rescue someone", "Research a project", "Return home", "Right a wrong", "Ruin an event", "Satisfy a desire or need", "Satisfy an obligation", "Save another", "Save face", "Set an example", "Silence someone", "Solve a mystery", "Spy on another", "Start a family", "Start a war", "Test someone’s limits", "Travel", "Usurp someone’s power", "Win a bet"
    ]},

    {"title": "d50 The locations is...", "id":"d50_LocationTrait", "roll":
    [ 
        "High", "Remote", "Exposed", "Small", "Broken", "Diverse", "Rough", "Dark", "Shadowy", "Contested", "Grim", "Wild", "Fertile", "Blocked", "Ancient", "Perilous", "Hidden", "Occupied", "Rich", "Big", "Savage", "Defended", "Withered", "Mystical", "Inaccessible", "Protected", "Abandoned", "Wide", "Foul", "Dead", "Ruined", "Barren", "Cold", "Blighted", "Low", "Beautiful", "Abundant", "Lush", "Flooded", "Empty", "Strange", "Corrupted", "Peaceful", "Forgotten", "Expansive", "Settled", "Dense", "Civilized", "Desolate", "Isolated"
    ]},
    
    {"title": "d100...", "id":"d100_NPCMotivationVerb", "roll":
    [ 
        "Advise", "Obtain", "Attempt", "Spoil", "Oppress", "Interact", "Create", "Abduct", "Promote", "Conceive", "Blight", "Progress", "Distress", "Possess", "Record", "Embrace", "Contact", "Pursue", "Associate", "Prepare", "Shepherd", "Abuse", "Indulge", "Chronicle", "Fulfill", "Drive", "Review", "Aid", "Follow", "Advance", "Guard", "Conquer", "Hinder", "Plunder", "Construct", "Encourage", "Agonize", "Comprehend", "Administer", "Relate", "Take", "Discover", "Deter", "Acquire", "Damage", "Publicize", "Burden", "Advocate", "Implement", "Understand", "Collaborate", "Strive", "Complete", "Compel", "Join", "Assist", "Defile", "Produce", "Institute", "Account", "Work", "Accompany", "Offend", "Guide", "Learn", "Persecute", "Communicate", "Process", "Report", "Develop", "Steal", "Suggest", "Weaken", "Achieve", "Secure", "Inform", "Patronize", "Depress", "Determine", "Seek", "Manage", "Suppress", "Proclaim", "Operate", "Access", "Refine", "Compose", "Undermine", "Explain", "Discourage", "Attend", "Detect", "Execute", "Maintain", "Realize", "Convey", "Rob", "Establish", "Overthrow", "Support"
    ]},

    {"title": "d100...", "id":"d100_NPCMotivationNoun", "roll":
    [ 
        "Wealth", "Hardship", "Affluence", "Resources", "Prosperity", "Poverty", "Opulence", "Deprivation", "Success", "Distress", "Contraband", "Music", "Literature", "Technology", "Alcohol", "Medicines", "Beauty", "Strength", "Intelligence", "Force", "The wealthy", "The population", "Enemies", "The public", "Religion", "The poor", "Family", "The elite", "Academia", "The forsaken", "The law", "The government", "The downtrodden", "Friends", "Criminals", "Allies", "Secret societies", "The world", "Military", "The church", "Dreams", "Discretion", "Love", "Freedom", "Pain", "Faith", "Slavery", "Enlightenment", "Racism", "Sensuality", "Dissonance", "Peace", "Discrimination", "Disbelief", "Pleasure", "Hate", "Happiness", "Servitude", "Harmony", "Justice", "Gluttony", "Lust", "Envy", "Greed", "Lazyness", "Wrath", "Pride", "Purity", "Moderation", "Vigilance", "Zeal", "Composure", "Charity", "Modesty", "Atrocities", "Cowardice", "Narcissism", "Compassion", "Valor", "Patience", "Advice", "Propaganda", "Science", "Knowledge", "Communications", "Lies", "Myths", "Riddles", "Stories", "Legends", "Industry", "New religions", "Progress", "Animals", "Ghosts", "Magic", "Nature", "Old religions", "Expertise", "Spirits"
    ]},

    {"title": "d50 Their secret is...", "id":"d50_NPCSecrets", "roll":
    [ 
        "Knows where a magic item is hidden", "Knows the best fishing spot", "Knows who the murderer is", "Is making liquor illegally", "Knows why no one swims in the millpond anymore", "Knows how to safely cook a poisonous fish", "Is having an affair", "Steals from his neighbors", "Is a habitual liar", "Is secretly related to another NPC", "Knows what happened to all the rats", "Is being blackmailed", "Drinks heavily", "Has a secret stash of funds", "Is beaten by his/her spouse", "Knows proper way to read a treasure map", "Is an obsessive collector or hoarder", "Beats offspring regularly", "Is quietly religious", "Knows location of a bandit hideout", "Knows a particular monster’s favorite snack", "Is a spy", "Hears voices in the graveyard", "Knows who really runs the neighborhood", "Knows where to contact the fey", "Is an assassin", "Has a secret illness", "Knows why no one in the village eats meat anymore", "Knows how to get the oracle to answer truthfully", "Engages in some deviant behavior", "Knows command word for a magic item", "Owes the local moneylender substantial funds", "Worships an evil deity", "Knows some local secret", "Has a secret identity", "Was a very different creature prior to reincarnation", "Knows how to placate an angry ghost", "Is a member of a secret local cult", "Is wanted for a crime", "Murdered spouse", "Makes secret donations", "Lost paladinhood due to cowardice", "Is a paladin working undercover", "Is the bastard child of a noble", "Knows when the heir to the throne sneaks away to visit an attractive peasant", "Is terrified of a particular monster type", "Has some orc blood in their family", "Has some troll blood in their family", "Knows where the meteor landed", "Knows someone is not what appears to be"
    ]},

    {"title": "d40 City seed is...", "id":"d40_SeedsCity", "roll":
    [ 
        "Steam", "Mobile", "Natural", "Poor", "Water", "Haunted", "Isolated", "Wealth", "Island", "Holy", "Color", "Dangerous", "Underground", "Metropolis", "Stone", "Pollution", "Sky", "Cold", "Tree", "Multicultural", "Industry", "Ruins", "Cliff", "Volcanic", "Rural", "Bridge", "Animal", "Fortification", "Tribal", "Ancient", "Segregation", "Crossroad", "Wall", "Militant", "Agriculture", "Dock", "Tower", "Death", "Otherworldly", "Glass"
    ]},
    
    {"title": "d100 Action is...", "id":"d100_OracleAction", "roll":
    [ 
        "Scheme","Clash","Weaken","Initiate","Create","Swear","Avenge","Guard","Defeat","Control","Break","Risk","Surrender","Inspect","Raid","Evade","Assault","Deflect","Threaten","Attack","Leave","Preserve","Manipulate","Remove","Eliminate","Withdraw","Abandon","Investigate","Hold","Focus","Uncover","Breach","Aid","Uphold","Falter","Suppress","Hunt","Share","Destroy","Avoid","Reject","Demand","Explore","Bolster","Seize","Mourn","Reveal","Gather","Defy","Transform","Persevere","Serve","Begin","Move","Coordinate","Resist","Await","Impress","Take","Oppose","Capture","Overwhelm","Challenge","Acquire","Protect","Finish","Strengthen","Restore","Advance","Command","Refuse","Find","Deliver","Hide","Fortify","Betray","Secure","Arrive","Affect","Change","Defend","Debate","Support","Follow","Construct","Locate","Endure","Release","Lose","Reduce","Escalate","Distract","Journey","Escort","Learn","Communicate","Depart","Search","Charge","Summon"
    ]},
    
    {"title": "d100 Theme is...", "id":"d100_OracleTheme", "roll":
    [ 
        "Risk", "Ability", "Price", "Ally", "Battle", "Safety", "Survival", "Weapon", "Wound", "Shelter", "Leader", "Fear", "Time", "Duty", "Secret", "Innocence", "Renown", "Direction", "Death", "Honor", "Labor", "Solution", "Tool", "Balance", "Love", "Barrier", "Creation", "Decay", "Trade", "Bond", "Hope", "Superstition", "Peace", "Deception", "History", "World", "Vow", "Protection", "Nature", "Opinion", "Burden", "Vengeance", "Opportunity", "Faction", "Danger", "Corruption", "Freedom", "Debt", "Hate", "Possession", "Stranger", "Passage", "Land", "Creature", "Disease", "Advantage", "Blood", "Language", "Rumor", "Weakness", "Greed", "Family", "Resource", "Structure", "Dream", "Community", "War", "Portent", "Prize", "Destiny", "Momentum", "Power", "Memory", "Ruin", "Mysticism", "Rival", "Problem", "Idea", "Revenge", "Health", "Fellowship", "Enemy", "Religion", "Spirit", "Fame", "Desolation", "Strength", "Knowledge", "Truth", "Quest", "Pride", "Loss", "Law", "Path", "Warning", "Relationship", "Wealth", "Home", "Strategy", "Supply"
    ]},

    {"title": "Their word is", "id":"GodboundWords", "roll":
    [ 
        "Artifice", "Beasts", "Bow", "Command", "Death", "Deception", "Earth", "Endurance", "Fertility", "Fire", "Health", "Journeying", "Knowledge", "Luck", "Might", "Night", "Passion", "Sea", "Sky", "Sorcery", "Sun", "Sword", "Time", "Wealth", "Shapeshifting", "Fate", "Birds", "Cities", "Dance", "Desert", "Desire", "Engineering", "Entropy", "Fear", "Insects", "Intoxication", "Madness", "Murder", "Music", "Network", "Protection", "Theft", "Underworld", "Vengeance", "War", "Winter", "Artificial Intelligence", "Dragon", "Faerie Queen", "Lich King", "Peak Human", "Freedom"
    ]},
    
    {"title": "d1 Test...", "id":"dTest", "roll":
    [ 
        "A warlock (d4): 1. Archfey Otherworldly Patron; 2. Fiend Otherworldly Patron; 3. Great Old One Otherworldly Patron; 4. A Test of Faith;",
    ]},

];


  