// peri.js
//


top.peri = [
    {"title": "d120 The character has the trait...", "id":"d120_CharacterTraits", "roll":
    [ 
        "Active", "Adventurous", "Affectionate", "Aggressive", "Agreeable", "Aloof", "Ambitious", "Angry", "Anxious", "Apathetic", "Arcane", "Arrogant", "Artistic", "Athletic", "Attractive", "Bitter", "Bold", "Brash", "Brave", "Calculating", "Careless", "Caring", "Cautious", "Charming", "Cheery", "Clever", "Clumsy", "Cold", "Conceited", "Confident", "Confused", "Connected", "Cooperative", "Corrupt", "Cowardly", "Critical", "Cruel", "Cunning", "Curious", "Dangerous", "Deceitful", "Dependent", "Determined", "Disabled", "Distracted", "Doomed", "Driven", "Dying", "Enigmatic", "Experienced", "Famous", "Fervent", "Friendly", "Generous", "Greedy", "Hardhearted", "Haunted", "Honest", "Hostile", "Hot-tempered", "Incompetent", "Infamous", "Influential", "Insensitive", "Insightful", "Intellectual", "Intolerant", "Jealous", "Kind", "Knowledgable", "Loyal", "Manipulative", "Meddler", "Moody", "Oblivious", "Observant", "Obsessed", "Oppressed", "Passive", "Patient", "Powerful", "Proud", "Quiet", "Quirky", "Reclusive", "Relaxed", "Religious", "Remorseful", "Resourceful", "Ruthless", "Secretive", "Selfish", "Serene", "Shrewd", "Sick", "Skilled", "Smug", "Sociable", "Sophisticated", "Stealthy", "Stern", "Stingy", "Stoic", "Strange", "Strong", "Stubborn", "Successful", "Suspicious", "Talented", "Timid", "Ugly", "Vain", "Vengeful", "Violent", "Wary", "Weak", "Wealthy", "Weary", "Wild", "Wise"
    ]},
    
    {"title": "d50 The character has the hook...", "id":"d50_CharacterHook", "roll":
    [ 
        "Missing a limb", "Visible prostetics", "Unusual hair, skin, or eye colors", "Scarring, either intentional or from old injuries", "Tic-like overuse of a particular word or phrase", "Specific unusual fragrance or cologne", "Constant fiddling with a particular item", "Visible sign of drug use", "Always seems to be in one particular mood", "Wear badges or marks of allegiance to a cause", "Extremely slow or fast pace of speech", "Wheezes, shakes, or other signs of infirmity", "Constantly with a drink to hand", "Always complaining about a group or organization", "Paranoid, possibly for justifiable reasons", "Insists on a particular location for all meetings", "Communicates strictly through a third party", "Abnormally obese or emaciated in build", "Always found with henchmen or friends", "Dresses far too young or old for them", "Unusually shabby or ill-kept clothing", "Cutting-edge fashion as they can afford", "Loud foreign clothing style", "Extremely muscular or spindly form", "Lacking or excessive in hair", "Unusually short or tall", "Taps toe or fingers constantly", "All motions are rough and vigorous", "Can't talk without gesturing", "Never looks directly at interlocutor", "Constantly glancing around", "Very obvious religious tokens are worn", "They have an unusual accent", "They're of an uncommon race for the area", "Extremely laconic or voluble", "Laughs at inappropriate moments", "Has some speech impediment", "Has a constant air of suspicion", "Has elaborate tattoos or skin-paintings", "Voice is extremely grating and unpleasant", "Recently wounded", "Missing an eye or facial feature", "Terrible taste in clothing", "Repeats himself constantly", "Speaks as little as possible", "Look diseased or have marks of disease", "Jewels or decorations in hair or beard", "Immaculate hairs/beard or fancy hairdo", "Speaks slowly, looks like drunk or dugged but is not", "Very young or very old"
    ]},

    {"title": "d100 The character is a...", "id":"d100_CharacterRole", "roll":
    [ 
        "Criminal", "Criminal", "Healer", "Healer", "Bandit", "Bandit", "Guide", "Guide", "Guide", "Performer", "Performer", "Performer", "Miner", "Miner", "Miner", "Mercenary", "Mercenary", "Mercenary", "Outcast", "Outcast", "Outcast", "Vagrant", "Vagrant", "Vagrant", "Forester", "Forester", "Forester", "Traveler", "Traveler", "Traveler", "Mystic", "Mystic", "Mystic", "Priest", "Priest", "Priest", "Sailor", "Sailor", "Sailor", "Pilgrim", "Pilgrim", "Pilgrim", "Thief", "Thief", "Thief", "Adventurer", "Adventurer", "Adventurer", "Forager", "Forager", "Forager", "Leader", "Leader", "Leader", "Guard", "Guard", "Guard", "Guard", "Artisan", "Artisan", "Artisan", "Artisan", "Scout", "Scout", "Scout", "Scout", "Herder", "Herder", "Herder", "Herder", "Fisher", "Fisher", "Fisher", "Fisher", "Warrior", "Warrior", "Warrior", "Warrior", "Warrior", "Hunter", "Hunter", "Hunter", "Hunter", "Hunter", "Raider", "Raider", "Raider", "Raider", "Raider", "Trader", "Trader", "Trader", "Trader", "Trader", "Farmer", "Farmer", "Farmer", "Farmer", "Farmer", "Unusual role"
    ]},

    {"title": "d100 The character has a simple goal of...", "id":"d100_CharacterSimpleGoals", "roll":
    [ 
        "Obtain an object", "Obtain an object", "Obtain an object", "Make an agreement", "Make an agreement", "Make an agreement", "Build a relationship", "Build a relationship", "Build a relationship", "Undermine a relationship", "Undermine a relationship", "Undermine a relationship", "Seek a truth", "Seek a truth", "Seek a truth", "Pay a debt", "Pay a debt", "Pay a debt", "Refute a falsehood", "Refute a falsehood", "Refute a falsehood", "Harm a rival", "Harm a rival", "Harm a rival", "Cure an ill", "Cure an ill", "Cure an ill", "Find a person", "Find a person", "Find a person", "Find a home", "Find a home", "Find a home", "Seize power", "Seize power", "Seize power", "Restore a relationship", "Restore a relationship", "Restore a relationship", "Create an item", "Create an item", "Create an item", "Travel to a place", "Travel to a place", "Travel to a place", "Secure provisions", "Secure provisions", "Secure provisions", "Rebel against power", "Rebel against power", "Rebel against power", "Collect a debt", "Collect a debt", "Collect a debt", "Protect a secret", "Protect a secret", "Protect a secret", "Spread faith", "Spread faith", "Spread faith", "Enrich themselves", "Enrich themselves", "Enrich themselves", "Protect a person", "Protect a person", "Protect a person", "Protect the status quo", "Protect the status quo", "Protect the status quo", "Advance status", "Advance status", "Advance status", "Defend a place", "Defend a place", "Defend a place", "Avenge a wrong", "Avenge a wrong", "Avenge a wrong", "Fulfill a duty", "Fulfill a duty", "Fulfill a duty", "Gain knowledge", "Gain knowledge", "Gain knowledge", "Prove worthiness", "Prove worthiness", "Prove worthiness", "Find redemption", "Find redemption", "Find redemption", "Escape from something", "Escape from something", "Resolve a dispute", "Resolve a dispute", "Resolve a dispute", "Roll twice", "Roll twice", "Roll twice", "Roll twice", "Roll twice"
    ]},

    {"title": "d100 The character has a compex goal of...", "id":"d100_CharacterComplexGoals", "roll":
    [ 
        "Access another dimension", "Alleviate feelings of guilt", "Amass an army", "Assume another’s identity", "Attend an event", "Attract a following", "Avoid responsibilities", "Become a martyr", "Become famous/infamous", "Become happy", "Become immortal", "Become wealthy", "Chronicle history", "Complete a mission", "Conquer a nation", "Continue a legacy", "Cure a disease", "Damage another’s reputation", "Delay a wedding", "Deliver a message", "Destroy a relationship", "Destroy an enemy", "Discover the truth", "Do good", "Earn money", "Eliminate a populace", "Eliminate a race", "Eliminate a threat", "Eliminate a weakness", "Enact revenge", "End a relationship", "End a war", "End suffering", "Enforce the law", "Entertain", "Escape punishment", "Establish a new identity", "Establish a relationship", "Exile someone", "Explore new territories", "Find a lost treasure", "Find a missing object or person", "Find someone", "Find spiritual enlightenment", "Frame someone", "Frighten", "Gain a reward", "Gain approval", "Gain attention", "Gain power", "Gain protection", "Gain trust", "Hide a secret", "Imprison another", "Improve someone’s social status", "Improve someone’s quality of life", "Increase a collection", "Inspire rebellion", "Investigate about something", "Lead others", "Make someone angry", "Make someone envious/jealous", "Make someone fail", "Make someone succeed", "Overturn a decision", "Pass an initiation", "Pay a debt", "Perform a religious ceremony", "Predict the future", "Prolong a war", "Promote peace", "Protect a reputation", "Prove self", "Prove someone’s innocence", "Reanimate the dead", "Reclaim property", "Regain control", "Regain fame or wealth", "Regain youth", "Relieve boredom", "Repair damage", "Rescue someone", "Research a project", "Return home", "Right a wrong", "Ruin an event", "Satisfy a desire or need", "Satisfy an obligation", "Save another", "Save face", "Set an example", "Silence someone", "Solve a mystery", "Spy on another", "Start a family", "Start a war", "Test someone’s limits", "Travel", "Usurp someone’s power", "Win a bet"
    ]},

    {"title": "d50 The locations is...", "id":"d50_LocationTrait", "roll":
    [ 
        "High", "Remote", "Exposed", "Small", "Broken", "Diverse", "Rough", "Dark", "Shadowy", "Contested", "Grim", "Wild", "Fertile", "Blocked", "Ancient", "Perilous", "Hidden", "Occupied", "Rich", "Big", "Savage", "Defended", "Withered", "Mystical", "Inaccessible", "Protected", "Abandoned", "Wide", "Foul", "Dead", "Ruined", "Barren", "Cold", "Blighted", "Low", "Beautiful", "Abundant", "Lush", "Flooded", "Empty", "Strange", "Corrupted", "Peaceful", "Forgotten", "Expansive", "Settled", "Dense", "Civilized", "Desolate", "Isolated"
    ]},
    
    {"title": "d100...", "id":"d100_NPCMotivationVerb", "roll":
    [ 
        "Advise", "Obtain", "Attempt", "Spoil", "Oppress", "Interact", "Create", "Abduct", "Promote", "Conceive", "Blight", "Progress", "Distress", "Possess", "Record", "Embrace", "Contact", "Pursue", "Associate", "Prepare", "Shepherd", "Abuse", "Indulge", "Chronicle", "Fulfill", "Drive", "Review", "Aid", "Follow", "Advance", "Guard", "Conquer", "Hinder", "Plunder", "Construct", "Encourage", "Agonize", "Comprehend", "Administer", "Relate", "Take", "Discover", "Deter", "Acquire", "Damage", "Publicize", "Burden", "Advocate", "Implement", "Understand", "Collaborate", "Strive", "Complete", "Compel", "Join", "Assist", "Defile", "Produce", "Institute", "Account", "Work", "Accompany", "Offend", "Guide", "Learn", "Persecute", "Communicate", "Process", "Report", "Develop", "Steal", "Suggest", "Weaken", "Achieve", "Secure", "Inform", "Patronize", "Depress", "Determine", "Seek", "Manage", "Suppress", "Proclaim", "Operate", "Access", "Refine", "Compose", "Undermine", "Explain", "Discourage", "Attend", "Detect", "Execute", "Maintain", "Realize", "Convey", "Rob", "Establish", "Overthrow", "Support"
    ]},

    {"title": "d100...", "id":"d100_NPCMotivationNoun", "roll":
    [ 
        "Wealth", "Hardship", "Affluence", "Resources", "Prosperity", "Poverty", "Opulence", "Deprivation", "Success", "Distress", "Contraband", "Music", "Literature", "Technology", "Alcohol", "Medicines", "Beauty", "Strength", "Intelligence", "Force", "The wealthy", "The population", "Enemies", "The public", "Religion", "The poor", "Family", "The elite", "Academia", "The forsaken", "The law", "The government", "The downtrodden", "Friends", "Criminals", "Allies", "Secret societies", "The world", "Military", "The church", "Dreams", "Discretion", "Love", "Freedom", "Pain", "Faith", "Slavery", "Enlightenment", "Racism", "Sensuality", "Dissonance", "Peace", "Discrimination", "Disbelief", "Pleasure", "Hate", "Happiness", "Servitude", "Harmony", "Justice", "Gluttony", "Lust", "Envy", "Greed", "Lazyness", "Wrath", "Pride", "Purity", "Moderation", "Vigilance", "Zeal", "Composure", "Charity", "Modesty", "Atrocities", "Cowardice", "Narcissism", "Compassion", "Valor", "Patience", "Advice", "Propaganda", "Science", "Knowledge", "Communications", "Lies", "Myths", "Riddles", "Stories", "Legends", "Industry", "New religions", "Progress", "Animals", "Ghosts", "Magic", "Nature", "Old religions", "Expertise", "Spirits"
    ]},

    {"title": "d50 Their secret is...", "id":"d50_NPCSecrets", "roll":
    [ 
        "Knows where a magic item is hidden", "Knows the best fishing spot", "Knows who the murderer is", "Is making liquor illegally", "Knows why no one swims in the millpond anymore", "Knows how to safely cook a poisonous fish", "Is having an affair", "Steals from his neighbors", "Is a habitual liar", "Is secretly related to another NPC", "Knows what happened to all the rats", "Is being blackmailed", "Drinks heavily", "Has a secret stash of funds", "Is beaten by his/her spouse", "Knows proper way to read a treasure map", "Is an obsessive collector or hoarder", "Beats offspring regularly", "Is quietly religious", "Knows location of a bandit hideout", "Knows a particular monster’s favorite snack", "Is a spy", "Hears voices in the graveyard", "Knows who really runs the neighborhood", "Knows where to contact the fey", "Is an assassin", "Has a secret illness", "Knows why no one in the village eats meat anymore", "Knows how to get the oracle to answer truthfully", "Engages in some deviant behavior", "Knows command word for a magic item", "Owes the local moneylender substantial funds", "Worships an evil deity", "Knows some local secret", "Has a secret identity", "Was a very different creature prior to reincarnation", "Knows how to placate an angry ghost", "Is a member of a secret local cult", "Is wanted for a crime", "Murdered spouse", "Makes secret donations", "Lost paladinhood due to cowardice", "Is a paladin working undercover", "Is the bastard child of a noble", "Knows when the heir to the throne sneaks away to visit an attractive peasant", "Is terrified of a particular monster type", "Has some orc blood in their family", "Has some troll blood in their family", "Knows where the meteor landed", "Knows someone is not what appears to be"
    ]},

    {"title": "d40 City seed is...", "id":"d40_SeedsCity", "roll":
    [ 
        "Steam", "Mobile", "Natural", "Poor", "Water", "Haunted", "Isolated", "Wealth", "Island", "Holy", "Color", "Dangerous", "Underground", "Metropolis", "Stone", "Pollution", "Sky", "Cold", "Tree", "Multicultural", "Industry", "Ruins", "Cliff", "Volcanic", "Rural", "Bridge", "Animal", "Fortification", "Tribal", "Ancient", "Segregation", "Crossroad", "Wall", "Militant", "Agriculture", "Dock", "Tower", "Death", "Otherworldly", "Glass"
    ]},
    
    {"title": "d100 Action is...", "id":"d100_OracleAction", "roll":
    [ 
        "Scheme","Clash","Weaken","Initiate","Create","Swear","Avenge","Guard","Defeat","Control","Break","Risk","Surrender","Inspect","Raid","Evade","Assault","Deflect","Threaten","Attack","Leave","Preserve","Manipulate","Remove","Eliminate","Withdraw","Abandon","Investigate","Hold","Focus","Uncover","Breach","Aid","Uphold","Falter","Suppress","Hunt","Share","Destroy","Avoid","Reject","Demand","Explore","Bolster","Seize","Mourn","Reveal","Gather","Defy","Transform","Persevere","Serve","Begin","Move","Coordinate","Resist","Await","Impress","Take","Oppose","Capture","Overwhelm","Challenge","Acquire","Protect","Finish","Strengthen","Restore","Advance","Command","Refuse","Find","Deliver","Hide","Fortify","Betray","Secure","Arrive","Affect","Change","Defend","Debate","Support","Follow","Construct","Locate","Endure","Release","Lose","Reduce","Escalate","Distract","Journey","Escort","Learn","Communicate","Depart","Search","Charge","Summon"
    ]},
    
    {"title": "d100 Theme is...", "id":"d100_OracleTheme", "roll":
    [ 
        "Risk", "Ability", "Price", "Ally", "Battle", "Safety", "Survival", "Weapon", "Wound", "Shelter", "Leader", "Fear", "Time", "Duty", "Secret", "Innocence", "Renown", "Direction", "Death", "Honor", "Labor", "Solution", "Tool", "Balance", "Love", "Barrier", "Creation", "Decay", "Trade", "Bond", "Hope", "Superstition", "Peace", "Deception", "History", "World", "Vow", "Protection", "Nature", "Opinion", "Burden", "Vengeance", "Opportunity", "Faction", "Danger", "Corruption", "Freedom", "Debt", "Hate", "Possession", "Stranger", "Passage", "Land", "Creature", "Disease", "Advantage", "Blood", "Language", "Rumor", "Weakness", "Greed", "Family", "Resource", "Structure", "Dream", "Community", "War", "Portent", "Prize", "Destiny", "Momentum", "Power", "Memory", "Ruin", "Mysticism", "Rival", "Problem", "Idea", "Revenge", "Health", "Fellowship", "Enemy", "Religion", "Spirit", "Fame", "Desolation", "Strength", "Knowledge", "Truth", "Quest", "Pride", "Loss", "Law", "Path", "Warning", "Relationship", "Wealth", "Home", "Strategy", "Supply"
    ]},

    {"title": "Their word is", "id":"GodboundWords", "roll":
    [ 
        "Artifice", "Beasts", "Bow", "Command", "Death", "Deception", "Earth", "Endurance", "Fertility", "Fire", "Health", "Journeying", "Knowledge", "Luck", "Might", "Night", "Passion", "Sea", "Sky", "Sorcery", "Sun", "Sword", "Time", "Wealth", "Shapeshifting", "Fate", "Birds", "Cities", "Dance", "Desert", "Desire", "Engineering", "Entropy", "Fear", "Insects", "Intoxication", "Madness", "Murder", "Music", "Network", "Protection", "Theft", "Underworld", "Vengeance", "War", "Winter", "Artificial Intelligence", "Dragon", "Faerie Queen", "Lich King", "Peak Human", "Freedom"
    ]},
    
    {"title": "The front is...", "id":"DungeonWorldFronts", "roll":
    [ 
        "Ambitious Organizations <br>Moves: </b>Attack someone by stealthy means (kidnapping, etc.), Attack someone directly (with a gang or single assailant), Absorb or buy out someone important (an ally, perhaps), Influence a powerful institution (change a law, manipulate doctrine), Establish a new rule (within the organization), Claim territory or resources, Negotiate a deal, Observe a potential foe in great detail. <b><br>The organization is (d6): 1. Misguided Good <i>(impulse: to do what is \"right\" no matter the cost)</i>; 2. a Thieves Guild <i>(impulse: to take by subterfuge)</i>; 3. a Cult <i>(impulse: to infest from within)</i>; 4. an Religious Organization <i>(impulse: to establish and follow doctrine)</i>; 5. a Corrupt Government <i>(impulse: to maintain the status quo)</i>; 6. a Cabal <i>(impulse: to absorb those in power, to grow)</i>;", 
        "Planar Forces <br>Moves: </b> Turn an organization (corrupt or infiltrate with influence), Give dreams of prophecy, Lay a Curse on a foe, Extract a promise in exchange for a boon, Attack indirectly through intermediaries, Rarely when the stars are right attack directly, Forster rivalries with other similar powers, Expose someone to a Truth (wanted or otherwise)<b><br>The planar force is (d6): 1. a God <i>(impulse: to gather worshippers)</i>; 2. a Demon Prince <i>(impulse: to open the gates of Hell)</i>; 3. an Elemental Lord <i>(impulse: to tear down creation to its component parts)</i>; 4. a Force of Chaos <i>(impulse: to destroy all semblance of order)</i>; 5. a Choir of Angels <i>(impulse: to pass judgement)</i>; 6. a Construct of Law <i>(impulse: to eliminate perceived disorder)</i>", 
        "Arcane Enemies <br>Moves: </b> Learn forbidden knowledge, Cast a spell over time and space, Attack a foe with magic (directly or otherwise), Spy on someone with a scrying spell, Recruit a follower or toady, Tempt someone with promises, Demand a sacrifice<b><br>The arcane enemy is (d6): 1. a Lord of the Undead <i>(impulse: to seek true immortality)</i>; 2. a Power-mad Wizard <i>(impulse: to seek magical power)</i>; 3. a Sentient Artifact <i>(impulse: to find a worthy wielder)</i>; 4. an Ancient Curse <i>(impulse: to ensnare)</i>; 5. a Chosen One <i>(impulse: to fulfill or resent their destiny)</i>; 6. a Dragon <i>(impulse: to hoard gold and jewel, to protect the clutch)</i>", 
        "Hordes <br>Moves: </b> Assault a bastion of civilization, Embrace internal chaos, Change direction suddenly, Overwhelm a weaker force, Perform a show of dominance, Abandon an old home to find a new one, Grow in size by breeding or conquest, Appoint a champion, Declare war and act upon that declaration without hesitation or deliberation<b><br>The horde is (d4): 1. Wandering Barbarians <i>(impulse: to grow strong, to drive their enemies before them)</i>; 2. Humanoid Vermin <i>(impulse: to breed, to multiply and consume)</i>; 3. Underground Dwellers <i>(impulse: to defend the complex from outsiders)</i>; 4. Plague of the Undead <i>(impulse: to spread)</i>", 
        "Cursed Places <br>Moves: </b>Vomit firth a lesser monster, Spread to an adjacent place, Lure someone in, Grow in intensity or depth, Leave a lingering effect on an inhabitant or visitor, Hide something from sight, Offer power, Dampen magic or increase its effects, Confuse or obfuscate truth or direction, Corrupt a natural law<b><br>The cursed place is (d6): 1. an Abandoned Tower <i>(impulse: to draw in the weak-willed)</i>; 2. a Unholy Ground <i>(impulse: to spawn evil)</i>; 3. an Elemental Vortex <i>(impulse: to grow, to tear apart reality)</i>; 4. a Dark Portal <i>(impulse: to disgorge demons)</i>; 5. a Shadowland <i>(impulse: to corrupt or consume the living)</i>; 6. a Place of Power <i>(impulse: to be controlled or tamed)</i>", 
    ]},

    {"title": "d1 Test...", "id":"dTest", "roll":
    [ 
        "A warlock (d4): 1. Archfey Otherworldly Patron; 2. Fiend Otherworldly Patron; 3. Great Old One Otherworldly Patron; 4. A Test of Faith;",
    ]},

    {"title": "The city origin is", "id":"SandboxCityOrigin", "roll":
    [ 
        "Ancestral Homeland (+2 Social)<br></b><i>The denizens have called this place home for a very long time. This place has levereged the investments of their ancestors and, in turn, have a strong unified culture and defined traditions.</i><b><br>", 
        "Ancient Industry (+2 Wealth)<br></b><i>At one point, long ago, this was a site of economic investment. The current denizens leverage the previous setter's forward thinking providing the area with economic tools.</i><b><br>", 
        "Defensive Location (+2 Military)<br></b><i>This site was founded due to it's providential location as a place of military defense. Perhaps this site is surrounded on three sides by rivers or perched on a hill.</i><b><br>", 
        "Ethnic exceptionalism (+2 Social)<br></b><i>The original citizens have xenophobic tendencies and a very rigid cultural standard that provides sense of unifying identity.</i><b><br>",
        "Idealists/Innovators (+2 Wealth)<br></b><i>This city was originally founded on an idea. The original founders were looking to eschew the old ways and explore at applying a new social or technological concept or idea. This risk has paid off. At least in the short-term.</i><b><br>", 
        "Mercantile Hub (+2 Wealth)<br></b><i>This city is hub of trade in the region and flexible and pragmatic with their laws to eek more business. To the point of being greedy.</i><b><br>", 
        "Militant Rebels (+2 Military)<br></b><i>The losers of a civil war, the allies and accomplicaces of a failed coup, or an exiled army unit found this settlement. Regardless of the current state, this place never lost its martial heritage.</i><b><br>", 
        "Outcasts (+2 Social)<br></b><i>The opposite of Ethnocentrist. This city was founded by the renegades and outcasts of other places. Possibly survivors or refugees. Whatever the cause, this diversity has become a source of strength.</i><b><br>", 
        "Spiritual Community (+2 Social)<br></b><i>The founders of this community were leaders of a religious or philosophical movement. Perhaps a major religious or education institution is still present here. Regardless, customs, laws, and traditions reflect this religious/spiritual/intellectual past providing a sense of unity.</i><b><br>", 
        "Survivalists (+2 Military)<br></b><i>The original inhabitants of this place were survivors and hardy folks. Whether refugees of a disaster, traveling explorers looking to settle down, or likeminded former woodsmen and woodswomen. Survivalist instincts and skills for self-preservation have left its mark in this community granting a familiarity in the tools of survival and sometimes, the tools of war.</i><b><br>"
    ]},

    {"title": "The city activity is", "id":"SandboxCityActivity", "roll":
    [ 
        "Defensive Might (+2 Military)<br></b><i>This settlement is the opposite of Military Might. Instead of being expansionist in nature, this place has a strong defensive network community.</i><b><br>",
        "Exceptional Craftsman (+2 Wealth)<br></b><i>This place is home to very high quality crafts and goods. Perhaps this place is specialized for a particular thing and is well known for that good.</i><b><br>",
        "Expanding Influence (+2 Military)<br></b><i>This city has very ambitious leaders and is spurned to believe it is the destined rulers of nearby lands. It has a strong martial bent.</i><b><br>",
        "Exploding Trade (+2 Wealth)<br></b><i>This locale is suffering a tremendous economic boom causing a surge in economic activity. This could be a new trade route, resource, or something else causing the trade explosion.</i><b><br>",
        "Military Might (+2 Military)<br></b><i>This city has a very strong martial and military tendency. Perhaps it is a military or mercenary base. The city is very supportive of its military might.</i><b><br>",
        "Place of Learning/Contemplation (+2 Wealth)<br></b><i>The city has a very deep rooted tendency to learn and values knowledge be it spiritual or intellectual. This has made the settlement wealthy with the influx of pilgrims, students, and/or travelers.</i><b><br>",
        "Political/Government (+2 Social)<br></b><i>This settlement is a hotbed of political activity. The locals are very in-tune with their community. Perhaps the local regional authorities have granted this location a council-like autonomy or has instated a governer with an ear to the ground.</i><b><br>",
        "Proselytizers (+2 Social)<br></b><i>This city is home to a very zealous group. Be it religious or philosophical, this place has a lot of spirit and cannot wait to spread it to the outlaying lands.</i><b><br>",
        "Resource provisioners (+2 Wealth)<br></b><i>This town is known for one particular resource. Grain, Timber, Fish etc and possesses a very strong industry around it.</i><b><br>",
        "Socially Battlehardened (+2 Social)<br></b><i>This town has survived a longstanded feud or overcame a particularly dividing social, political, or economic situation and came out greater than before. The solution could have been one of compromise or defeat. Regardless, this place has a stronger sense of identity.</i><b><br>"
    ]},

    {"title": "The obstacle the city faces is", "id":"SandboxCityObstacle", "roll":
    [ 
        "Seedy Reputation and/or Poverty (Social/Culture change)<br></b><i>This is a hive of scum and villany. Greedy merchants, thieves, and conmen. This imbalance of wealth has caused immense amounts of poverty. The golden rule is king: the one with gold makes the rules. Social upheaval and cultural change is required to fix this problem of corrupt, greedy leaders.</i><b>",
        "Economic/Class Issues (Social/Culture change)<br></b><i>This location is full of spite between economic groups. Fixing this problem requires fixing the socio economic hierarchy</i><b>",
        "Infertile lands (Wealth/Investment)<br></b><i>The land here is barren or just not good for growing crops. It could be physical or magical in nature.Turning the land here into arable formland is a formidable request and undertaking requiring irrigation or magical cleansing/terraforming.</i><b>",
        "Cynicism (Social/Culture change)<br></b><i>The locals here have suffered for so much they have grown cynical or complacent. Alternatively it could be about societal disunity. Society will require a new beacon of hope in order to lead social change.</i><b>",
        "Demagogue (Social/Force)<br></b><i>The populace is under the spell of a demagogue. Often religious in nature, the populace has been persuaded by a very charismatic leader who is usurping power and defying customs and traditions. It could also be a shadowy cult at work behind the scenes.</i><b>",
        "Old Ways (Wealth/Knowledge)<br></b><i>The populace here is very traditional and conservative in habits even when these habits are detrimental. An example of this could be xenophobia or some odd custom. Education and convincing is required in order for progress to flourish.</i><b>",
        "Riotous Protests (Military/Investement)<br></b><i>The local population is in the middle of a turmoil or open revolt. The threat is internal in nature and the police and law enforcers are ill equipped to handle the uprising.</i><b>",
        "Secret Society (Social/Culture change)<br></b><i>There is a shadow organization with tendrils throughout the ruling government. They have the true power and rule by fear and force behind coopted or willing representatives.</i><b>",
        "Recovery (Wealth/Investment)<br></b><i>Something in the past has destroyed a lot of the place's assets and industry. Many areas of this place will need to be rebuilt from a passing storm or natural disaster or war.</i><b>",
        "Raiders (Military/Investement)<br></b><i>Monstrous beasts and brutes and/or Bandit Raiders run rampant over the lands. The current defenses of the area are inadequate to handle the threat and require investment and/or aid.</i><b>",
        "Natural Problems (Wealth/Investment)<br></b><i>The land around the site is precarious. It could be poor traveling roads or conditions. It could be floods, landslides, bad water, storms, or blights. Civilization can be brought here but will require investment and innovation in order to secure trade.</i><b>"
    ]},
];


  